var weapons =
["landmine",
"bow",
"melee",
"paintball",
"basketball",
"octobrush",
"fidget spinner",
"assault rifle",
"frisbee",
"tank"];

var melee =
["sword",
"knife",
"golf club",
"baseball bat",
"stick",
"potato",
"shoe",
"dead platypus",
"65",
"diamond sword",
"dual swords",
"TI-Nspire",
"folding chair",
"steam controller",
"pear",
"war axe",
"greatsword",
"Victorian broadsword",
"shortsword",
"mace",
"bottle of vodka"];

var itemsToFind =
["fruit tree",
"poisonous fruit tree",
"clean water",
"clean coal",
"clean Cole",
"OCC vending machine",
"wild Ohio Fried Chicken",
"glasses that cure color-blindness",
"bleach gummy bottle",
"paintball",
"used Band-Aid",
"clean water",
"pack of condoms",
"tent",
"biology textbook",
"bucket of KFC",
"tin of Donald Trump's bronzer",
"Emoji Movie on laserdisc",
"anthology of life-changing poems",
"quenched and tempered steel",
"VIP ticket to Tana Mojo concert",
"unicorn",
"spiritual enlightenment in a Villanova brochure",
"Lapras",
"diamond pickaxe",
"Stalin mustache"];

var causeAndEffect =
["fruit tree",
"eats fruit and gains one point in strength",
"poisonous fruit tree",
"eats a poisonous fruit",
"clean water",
"drinks clean water and gains one point in constitution",
"clean coal",
"uses coal to cook food",
"clean Cole",
"uses clean Cole as food",
"OCC vending machine",
"gets a tin of Altoids",
"wild Ohio Fried Chicken",
"random chicken",
"glasses that cure color-blindness",
"is no longer color-blind",
"bleach gummy bottle",
"eats bleach gummy bottle",
"used Band-Aid",
"random bandaid",
"pack of condoms",
"safe dating",
"tent",
"constructs a tent",
"biology textbook",
"reads a biology textbook and falls asleep",
"bucket of KFC",
"eats KFC",
"tin of Donald Trump's bronzer",
"becomes as orange as Donald Trump and dies of chemical poisoning",
"Emoji Movie on laserdisc",
"dies of pure cancer after watching the Emoji Movie",
"anthology of life-changing poems",
"\'s life gets changed by poetry",
"quenched and tempered steel",
"constructs a geometrically stable truss",
"VIP ticket to Tana Mojo concert",
"gets assaulted by a toothbrush at Tana Mojo concert",
"unicorn",
"pets the pink fluffy unicorn",
"spiritual enlightenment in a Villanova brochure",
"sees the light and adheres to the all-boy advantage",
"Agrawal star",
"jealousy",
"diamond pickaxe",
"mines diamond ore"];

var killCauseAndEffect =
["landmine",
"random mine",
"bow",
"shoots",
"melee",
"kills",
"paintball",
"brings one less paintball, so",
"basketball",
"dunks on",
"octobrush",
"splats",
"fidget spinner",
"spins fidget spinner fatally at",
"assault rifle",
"shoots",
"frisbee",
"decapitates",
"tank",
"murders",
"Stalin mustache",
"gulag"];

var shelter =
["cave",
"tree",
"cardboard box",
"geometrically stable truss",
"House of the Seven Gables"];

var cornucopia =
["run",
"supply",
"weapon",
"battle"
];

var sponsor =
["empty box",
"paintball",
"used Band-Aid",
"clean water",
"pack of condoms",
"tent",
"biology textbook",
"bucket of KFC",
"tin of Donald Trump's bronzer",
"Emoji Movie on laserdisc",
"anthology of life-changing poems",
"quenched and tempered steel",
"VIP ticket to Tana Mojo concert",
"Agrawal star",
"Lapras",
"diamond pickaxe"];

var misc =
["wanders around",
"picks flowers",
"heils Hitler",
"hails Hortler",
"talks to",
"drops a rant against",
"levels up",
"sings us a song",
"is the sheriff",
"plays some pranks (GONE WRONG GONE SEXUAL)",
"realizes maverick isn't all yellow",
"loses the game",
"cries",
"has nightmares",
"stabs asparagus",
"runs out of ammunition",
"is accused of mansplaining",
"Disney star takes",
"gets doxxed by keemstar",
"hides in a river",
"hides from",
"eats",
"attaches a measuring tape to a toaster",
"gains Disney Channel flo"];

var injury =
["gets a cold",
"gets the flu",
"gets mono",
"gets strep throat",
"loses 0.13 GPA points, and is severely injured",
"is stung by BEES",
"battles and wounds",
"sends a mass mail",
"goes deaf due to Jake Paul",
"triggered",
"gets carpal tunnel syndrome from playing osu",
"gets osteoporosis",
"gets crippling depression",
"tries to break the fourth wall",
"prank calls"];

var injEffect =
["bow",
"injures",
"melee",
"injures",
"paintball",
"gets hit by a paintball shot by",
"basketball",
"gets juked by",
"octobrush",
"wounds",
"fidget spinner",
"spins fidget spinner nonfatally at",
"assault rifle",
"shoots and grazes"];

var variousDeaths =
["strangles",
"breaks",
"dies of Ebola",
"gets crushed by an unstable truss",
"forgets to get the AED for",
"gets burned to death from",
"hangs",
"decides to take a permanent nap",
"falls off a cliff while playing Pokemon Go",
"yells \"woag wiag wiag\" at",
"gets nuked from orbit by",
"chokes on crabapples in cheeks",
"forgets how to breathe",
"uses dank memes to kill",
"navy seals",
"unsafe dating",
"gets hit by a hurricane"];

var doubleDeath =
["strangles",
"forgets to get the AED for",
"gets nuked from orbit by",
"gets memed to death by",
"uses dank memes to kill"];

var options =
["weapons",
"items",
"use",
"shelter",
"use",
"misc",
"injury",
"use",
"death",
"heal",
"items",
"use",
"injury",
"use"];

var itemsThatGivePoints = [
"fruit tree",
"clean water",
"glasses that cure color-blindness",
"anthology of life-changing poems"];

var vowels = ["a","e","i","o","u"];
